from rest_framework.test import APITestCase
from .models import Category, Skill
from django.urls import reverse

class CategoryAPITests(APITestCase):
    def setUp(self):
        self.cat1 = Category.objects.create(name="Design", icon="palette", description="Design projects")
        self.cat2 = Category.objects.create(name="Programming", icon="code", description="Programming jobs")

    def test_category_list(self):
        url = reverse('category-list')  # Generated by DRF router
        res = self.client.get(url)
        self.assertEqual(res.status_code, 200)
        names = [x['name'] for x in res.data]
        self.assertIn("Design", names)
        self.assertIn("Programming", names)

    def test_category_detail(self):
        url = reverse('category-detail', args=[self.cat1.id])
        res = self.client.get(url)
        self.assertEqual(res.status_code, 200)
        self.assertEqual(res.data['name'], "Design")
