# Generated by Django 4.2 on 2025-07-21 03:01

from django.db import migrations, models
import django.db.models.deletion
import gigs.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_clientprofile_profile_picture'),
        ('core', '0001_initial'),
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=2000)),
                ('budget_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timeline_days', models.PositiveIntegerField()),
                ('project_scope', models.CharField(blank=True, choices=[('one_time', 'One-time'), ('ongoing', 'Ongoing')], max_length=20, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_freelancers', models.ManyToManyField(blank=True, related_name='applied_proposals', to='profiles.freelancerprofile')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='profiles.clientprofile')),
                ('required_skills', models.ManyToManyField(blank=True, related_name='proposals', to='core.skill')),
                ('selected_freelancer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_proposals', to='profiles.freelancerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_time', models.PositiveIntegerField(help_text='Delivery time in days')),
                ('revisions', models.PositiveIntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to=gigs.models.service_image_upload_path)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='profiles.freelancerprofile')),
                ('skills', models.ManyToManyField(blank=True, related_name='services', to='core.skill')),
            ],
        ),
        migrations.DeleteModel(
            name='Gig',
        ),
    ]
