# Generated by Django 4.2 on 2025-07-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_proposal_service_delete_gig'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='delivery_time',
            field=models.PositiveIntegerField(),
        ),
    ]
