# Generated by Django 4.2 on 2025-07-28 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0004_serviceorder'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serviceorder',
            unique_together=set(),
        ),
    ]
