# Generated by Django 4.2 on 2025-07-30 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_clientprofile_profile_picture'),
        ('gigs', '0005_alter_serviceorder_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_orders', to='profiles.clientprofile')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_orders', to='profiles.freelancerprofile')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='gigs.proposal')),
            ],
            options={
                'unique_together': {('proposal', 'freelancer')},
            },
        ),
    ]
