# Generated by Django 4.2 on 2025-07-30 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0006_proposalorder'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proposalorder',
            unique_together=set(),
        ),
    ]
