# Generated by Django 4.2 on 2025-07-06 08:41

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='certificate',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=profiles.models.education_certificate_path, validators=[profiles.models.validate_certificate_file]),
        ),
        migrations.AlterField(
            model_name='experience',
            name='certificate',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=profiles.models.experience_certificate_path, validators=[profiles.models.validate_certificate_file]),
        ),
    ]
