# Generated by Django 4.2 on 2025-05-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
