# Generated by Django 4.2 on 2025-07-11 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_alter_education_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='verification',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='country',
            field=models.CharField(default=2, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='account_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], max_length=10),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='budget_range',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='company_description',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='company_size',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='expected_timeline',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='last_name',
            field=models.CharField(default=12, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='location',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit-card', 'Credit Card'), ('debit-card', 'Debit Card'), ('paypal', 'PayPal'), ('bank-transfer', 'Bank Transfer'), ('stripe', 'Stripe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='payment_timing',
            field=models.CharField(blank=True, choices=[('upfront', '100% Upfront'), ('milestone-based', 'Milestone-based'), ('upon-completion', 'Upon Completion'), ('monthly', 'Monthly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='previous_experiences',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.client_profile_picture_path),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='project_frequency',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='quality_importance',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='website',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='working_hours',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
