# Generated by Django 4.2 on 2025-05-30 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_freelancerprofile_github_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancerprofile',
            old_name='location_name',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='freelancer',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='link',
            new_name='project_link',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='longitude',
        ),
        migrations.AddField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='first_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='last_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='freelancers', to='profiles.skill'),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
