# Generated by Django 4.2 on 2025-05-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_location_name_freelancerprofile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='cerificate',
            field=models.FileField(blank=True, null=True, upload_to='freelancers/certifications/experience_certificates'),
        ),
    ]
