# Generated by Django 4.2 on 2025-07-11 06:13

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_clientprofile_verification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=profiles.models.client_profile_picture_path),
        ),
    ]
