# Generated by Django 4.2 on 2025-05-31 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_experience_cerificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='cerificate',
            new_name='certificate',
        ),
    ]
