# Generated by Django 4.2 on 2025-10-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_clientprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='company_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='company_size',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='industry',
            field=models.CharField(max_length=128),
        ),
    ]
