# Generated by Django 4.2 on 2025-10-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_clientprofile_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='monthly_budget',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='preferred_communications',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='project_budget',
        ),
    ]
