# Generated by Django 4.2 on 2025-10-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_clientprofile_monthly_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='previous_experiences',
        ),
    ]
