# Generated by Django 4.2 on 2025-06-01 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_education_certificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certification',
        ),
    ]
