# Generated by Django 4.2.25 on 2025-10-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_clientprofile_previous_experiences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='company_description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='company_size',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
