# Generated by Django 4.2 on 2025-06-02 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_portfolio_github_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientprofile',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='clientprofile',
            old_name='location_name',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='longitude',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='account_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], default=None, max_length=16),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='budget_range',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='business_goals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='company_size',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='current_challenges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='expected_timeline',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='last_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='monthly_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='payment_method',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='payment_timing',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='preferred_communications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='previous_experiences',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='project_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='project_frequency',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='project_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='quality_importance',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='working_hours',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
