# Generated by Django 4.2 on 2025-06-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_rename_full_name_clientprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
