# Generated by Django 4.2 on 2025-06-08 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_clientprofile_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientprofile',
            old_name='about',
            new_name='company_description',
        ),
    ]
