# Generated by Django 4.2 on 2025-06-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('profiles', '0015_remove_skill_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='freelancers', to='core.skill'),
        ),
    ]
