# Generated by Django 4.2 on 2025-06-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_freelancerprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='client_profile_picture_path'),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='freelancer_profile_picture_path'),
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['user'], name='profiles_cl_user_id_8ca3ca_idx'),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['profile'], name='profiles_ed_profile_5e5b90_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['profile'], name='profiles_ex_profile_7d6e70_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancerprofile',
            index=models.Index(fields=['user'], name='profiles_fr_user_id_5e3ae0_idx'),
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['profile'], name='profiles_la_profile_2a95a2_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['profile'], name='profiles_po_profile_010b85_idx'),
        ),
        migrations.AddIndex(
            model_name='sociallinks',
            index=models.Index(fields=['user'], name='profiles_so_user_id_fecbbc_idx'),
        ),
    ]
