# Generated by Django 4.2 on 2025-08-07 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_conversationreadstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deadline', models.DateField()),
                ('terms', models.TextField(blank=True)),
                ('milestones', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Client Acceptance'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('workflow_status', models.CharField(choices=[('planning', 'planning'), ('draft', 'draft'), ('submitted', 'submitted'), ('negotiation', 'negotiation'), ('accepted', 'accepted'), ('started', 'started'), ('milestone-1', 'milestone-1'), ('review', 'review'), ('completed', 'completed'), ('paid', 'paid')], default='planning', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='messaging.conversation')),
            ],
        ),
    ]
