# Generated by Django 4.2 on 2025-08-07 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0007_alter_proposalorder_unique_together'),
        ('messaging', '0003_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='conversation',
        ),
        migrations.AddField(
            model_name='contract',
            name='proposal_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='gigs.proposalorder'),
        ),
        migrations.AddField(
            model_name='contract',
            name='service_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='gigs.serviceorder'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('proposal_order__isnull', True), ('service_order__isnull', False)), models.Q(('proposal_order__isnull', False), ('service_order__isnull', True)), _connector='OR'), name='contract_order_exclusive'),
        ),
    ]
