# Generated by Django 4.2 on 2025-08-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_remove_contract_conversation_contract_proposal_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='voice_duration',
            field=models.IntegerField(blank=True, help_text='Duration of voice message in seconds', null=True),
        ),
    ]
