# Generated by Django 4.2 on 2025-09-12 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_paymentrequest_delete_callrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='payment_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='messaging.paymentrequest'),
        ),
    ]
