# Generated by Django 4.2 on 2025-09-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_message_payment_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='workflow_status',
            field=models.CharField(choices=[('planning', 'planning'), ('advance', 'advance'), ('draft', 'draft'), ('submitted', 'submitted'), ('in-progress', 'in-progress'), ('milestone-1', 'milestone-1'), ('revision', 'revision'), ('final-review', 'final-review'), ('completed', 'completed'), ('paid', 'paid')], default='planning', max_length=50),
        ),
    ]
