# Generated by Django 4.2 on 2025-05-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_category_education_experience_freelancerprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
