# Generated by Django 4.2 on 2025-05-19 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_education_user_remove_experience_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
