name: Deploy SkillConnect

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Frontend (on GitHub)
        run: |
          cd frontend
          echo "VITE_API_URL=https://skillconnect.buzz" > .env
          echo "VITE_WS_URL=wss://skillconnect.buzz" >> .env
          echo "VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }}" >> .env
          echo "VITE_RAZORPAY_KEY_ID=${{ secrets.VITE_RAZORPAY_KEY_ID }}" >> .env

          npm install
          npm run build


      - name: Deploy to GCP
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/skillconnect
            git pull origin main

            cd backend
            source venv/bin/activate
            pip install -r requirements.txt
            python3 manage.py migrate
            python3 manage.py collectstatic --noinput
            sudo systemctl restart daphne
            sudo systemctl restart celery
            sudo systemctl restart nginx

      - name: Upload Build Folder
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontend/dist/*"
          target: "/home/skillconnect717/skillconnect/frontend/dist"
          strip_components: 2